[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

# Gas optimization
optimizer = true
optimizer_runs = 200
via_ir = true

# Security settings
auto_detect_solc = false
bytecode_hash = "none"
cbor_metadata = false

# File access permissions
fs_permissions = [{ access = "read", path = "." }]

# Hyperliquid configuration
[rpc_endpoints]
hyperliquid_testnet = "https://rpc.hyperliquid-testnet.xyz/evm"
hyperliquid_mainnet = "https://hlh-builders-jp-mainnet.hyperpc.app?use-upstream=hlnode"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "short"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options