[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

# Hyperliquid configuration
[rpc_endpoints]
hyperliquid_testnet = "https://api.hyperliquid-testnet.xyz/evm"
hyperliquid_mainnet = "https://api.hyperliquid.xyz/evm"

[etherscan]
hyperliquid_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.hyperliquid-testnet.xyz" }
hyperliquid_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.hyperliquid.xyz" }

# Gas optimization
optimizer = true
optimizer_runs = 200
via_ir = true

# Security settings
auto_detect_solc = false
bytecode_hash = "none"
cbor_metadata = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "short"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
